name: Matrix demo
on: push
jobs: 
  build:
    strategy:
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }} 
    steps: 
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node-js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm ci 
      - name: build project 
        run: npm run build
