name: reusable workflow
on: 
  workflow_call:
    inputs:
      artifact_name:
        description: the name of deployable artifact file 
        required: false
        default: dist
        type: string 
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/download-artifact@v4
        with: 
          name: ${{ inputs.artifact_name }}
      - name: list files
        run: ls
      - name: output information
        run: echo "this is reusable workflow"